"""Keep reviewed local release policy when shared templates are regenerated."""

import argparse
import re
from pathlib import Path

GENERATED = ("quality-gate.yml", "release-pipeline.yml")
GENERATED_HEADER = "# Generated by venus-os-ci-toolkit/scripts/install_release.py;"
ACTION = "step-security/harden-runner"
PIN_LINE = re.compile(
    r"(?m)^(?P<prefix>[ \t]*(?:- )?uses: )"
    + re.escape(ACTION)
    + r"@(?P<sha>[0-9a-f]{40}) # (?P<version>v[0-9]+\.[0-9]+\.[0-9]+)[ \t]*$"
)
BEGIN = "<!-- BEGIN local release-note requirements -->"
END = "<!-- END local release-note requirements -->"
NOTES_ANCHOR = "## Publication and deployment\n"


def reviewed_runner_pin(root: Path) -> str:
    """Use the non-generated build adapter as the local reviewed pin authority."""
    source = (root / ".github/workflows/release-build.yml").read_text()
    matches = list(PIN_LINE.finditer(source))
    pins = {(match["sha"], match["version"]) for match in matches}
    if len(matches) != source.count(ACTION + "@") or len(pins) != 1:
        raise ValueError("Build adapter must declare one unambiguous immutable harden-runner pin")
    sha, version = pins.pop()
    return f"{ACTION}@{sha} # {version}"


def runner_overlay(path: Path, pin: str, *, check: bool = False) -> None:
    """Restore the reviewed pin while retaining the generator's workflow structure."""
    source = path.read_text()
    matches = list(PIN_LINE.finditer(source))
    if (
        not source.startswith(GENERATED_HEADER)
        or not matches
        or len(matches) != source.count(ACTION + "@")
    ):
        raise ValueError(f"{path.name}: generated harden-runner structure changed; review overlay")
    updated = PIN_LINE.sub(lambda match: match["prefix"] + pin, source)
    if updated != source:
        if check:
            raise ValueError(f"{path.name}: harden-runner differs from reviewed build adapter")
        path.write_text(updated)


def notes_overlay(root: Path, *, check: bool = False) -> None:
    """Insert the non-generated local changelog requirements in the generated runbook."""
    path = root / "RELEASING.md"
    source = path.read_text()
    notes = (root / "docs/release-notes-policy.md").read_text().strip()
    if not notes or BEGIN in notes or END in notes:
        raise ValueError("Local release-note requirements must be nonempty and unambiguous")
    block = f"{BEGIN}\n\n{notes}\n\n{END}\n\n"
    if source.count(NOTES_ANCHOR) != 1:
        raise ValueError("Release runbook structure changed; review local requirements")
    if BEGIN in source or END in source:
        if source.count(BEGIN) != 1 or source.count(END) != 1:
            raise ValueError("Ambiguous local release-note requirements in runbook")
        before, rest = source.split(BEGIN)
        _, after = rest.split(END)
        source_without_block = before + after.lstrip("\n")
    else:
        source_without_block = source
    updated = source_without_block.replace(NOTES_ANCHOR, block + NOTES_ANCHOR)
    if updated != source:
        if check:
            raise ValueError("Release runbook is missing current local release-note requirements")
        path.write_text(updated)


def overlay(root: Path, *, check: bool = False) -> None:
    """Apply or verify all local generation constraints without changing policy."""
    pin = reviewed_runner_pin(root)
    for name in GENERATED:
        runner_overlay(root / ".github/workflows" / name, pin, check=check)
    notes_overlay(root, check=check)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    overlay(args.root, check=args.check)
