name: 'Auto Approve PRs'
description: 'Auto-approve Dependabot, Renovate, and 4alvit PRs'

"on":
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'renovate[bot]' ||
      github.event.pull_request.user.login == '4alvit'
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          github-token: ${{ secrets.BOT_PAT }}
          review-message: 'Auto-approved by CI'
