name: Scorecard security audit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 2 * * 3'  # Weekly on Wednesdays at 2:30 AM UTC

permissions:
  contents: read
  # Needed to upload the results to code-scanning dashboard.
  security-events: write
  # Needed for GitHub OIDC token
  id-token: write

jobs:
  scorecard:
    name: Scorecard
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/scorecard.yml@5b18667880c7a0154b7c7e6686042eff5f47cdb7
